networks:
  appnetwork:
    name: appnetwork  # Esto fuerza el nombre exacto sin prefijos

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-sobunny
    restart: always
    ports:
      - "${PORT_NGINX:-80}:80"
      - "${PORT_SSL:-443}:443"  # Habilita el puerto 443 para SSL
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/${NGINX_CONF_FILE:-default.conf}:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/certs:/etc/nginx/certs  # Monta la carpeta de certificados
      # - /etc/letsencrypt:/etc/letsencrypt  # Monta la carpeta de certificados de Let's Encrypt
    depends_on:
      - php
    networks:
      - appnetwork

  mysql:
    image: mysql:5.7.32
    container_name: mysql-sobunny
    restart: always
    tty: true
    ports:
      - "${PORT_MYSQL:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pA7kE3xW!s9QmL2z
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pA7kE3xW!s9QmL2z
      - MYSQL_DATABASE=sobynny_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/sobunny.sql:/docker-entrypoint-initdb.d/sobunny.sql
    networks:
      - appnetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma-sobunny
    environment:
      PMA_HOST: mysql-sobunny
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "${PORT_PHPMYADMIN:-81}:80"      
    networks:
      - appnetwork
    depends_on:
      mysql:
        condition: service_healthy

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-sobunny
    restart: always
    volumes:
      - ./:/var/www/html/
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.env:/var/www/html/.env
    ports:
      - "${PORT_PHP:-9000}:9000"
    networks:
      - appnetwork
    depends_on:
      mysql:
        condition: service_healthy
  
volumes:
  mysql_data:
